defaults:
  - _self_
  - data: dogs
  - model: mdogs
  - paths: default
  - callbacks: default
  - logger: default
  - trainer: default

paths:
  output_dir: ${hydra:runtime.cwd}/outputs

ckpt_path: ${paths.output_dir}
input_path: ${hydra:runtime.cwd}/samples/input/
output_path: ${hydra:runtime.cwd}/samples/output/

num_images: 2
seed: 42